surface.CreateFont( "JMSF", {
	font = "Counter-Strike",
	extended = false,
	size = 60,
	weight = 50,
	blursize = 0.9,
	scanlines = 0,
	antialias = false,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = true,
	shadow = true,
	additive = false,
	outline = true,
} )

surface.CreateFont( "JMSF_COUNT", {
	font = "Counter-Strike",
	extended = false,
	size = 40,
	weight = 80,
	blursize = 0,
	scanlines = 2,
	antialias = false,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "JMSF_CHEAP", {
	font = "csd", 
	extended = false,
	size = 60,
	weight = 50,
	blursize = 0,
	scanlines = 2,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = true,
} )

surface.CreateFont( "Console", {
	font = "Roboto-Regular",
	extended = false,
	size = 22,
	weight = 10,
	blursize = 0,
	scanlines = 2,
	antialias = false,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} 	)

surface.CreateFont( "JMSF_ITEM", {
	font = "Roboto-Regular",
	extended = false,
	size = 10,
	weight = 20,
	blursize = 0,
	scanlines = 2,
	antialias = false,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} 	)